name: weather_firebase_app
description: Weather + Firebase App

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  google_sign_in: ^6.1.6




flutter:
  uses-material-design: true
